host: "shrouded-sands-8342.herokuapp.com"
email_from: 'notify@shrouded-sands-8342.herokuapp.com'

# Heroku app name
heroku_name: "shrouded-sands-8342"

# Blog name
blog_title: 'Simple Blog'

# Google analytics code
ga_enabled: true
ga_code: 'UA-2XXXXX305-7'
